import type { Chain, Cost, Project, Tag } from "./types"

export const TAGS: Tag[] = [
  { id: "new", name: "New Listing", color: "emerald-500" },
  { id: "free", name: "FREE", color: "emerald-600" },
  { id: "liquidity", name: "Liquidity", color: "yellow-500" },
  { id: "bridge", name: "Bridge Liquidity", color: "orange-500" },
  { id: "gas", name: "Gas Fees", color: "blue-500" },
  { id: "eth", name: "ETH", color: "blue-600" },
  { id: "trading", name: "Trading", color: "red-500" },
]

export const CHAINS: Chain[] = [
  { id: "solana", name: "Solana", color: "emerald-600" },
  { id: "evm", name: "Ethereum/EVM", color: "blue-600" },
  { id: "bnb", name: "BNB", color: "yellow-600" },
  { id: "base", name: "Base", color: "blue-500" },
  { id: "multichain", name: "Multichain", color: "purple-500" },
  { id: "independent", name: "Independent", color: "gray-500" },
]

export const COSTS: Cost[] = [
  { id: "free", name: "FREE", color: "emerald-600" },
  { id: "ended", name: "Ended", color: "gray-500" },
  { id: "bridge", name: "Bridge Liquidity", color: "orange-500" },
  { id: "liquidity", name: "Liquidity", color: "yellow-600" },
  { id: "gas", name: "Gas Fees", color: "blue-500" },
]

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: "1",
    name: "Grass Protocol",
    image: "/placeholder.svg?height=24&width=24",
    description: "The Data Layer of AI",
    chain: "Solana",
    cost: "FREE",
    backers: "Polychain, Tribe Capital, etc.",
    stage: "Mainnet",
    isNew: true,
    addedAt: new Date("2024-02-24"),
  },
  {
    id: "2",
    name: "Rabby Wallet",
    image: "/placeholder.svg?height=24&width=24",
    description: "Crypto Wallet",
    chain: "Ethereum/EVM",
    cost: "FREE",
    backers: "n/a",
    stage: "Mainnet",
    isNew: true,
    addedAt: new Date("2024-02-23"),
  },
  {
    id: "3",
    name: "Rainbow Wallet",
    image: "/placeholder.svg?height=24&width=24",
    description: "Crypto Wallet",
    chain: "Ethereum/EVM",
    cost: "FREE",
    backers: "Seven Seven Six, Polygon, etc.",
    stage: "Mainnet",
  },
  {
    id: "4",
    name: "io.net",
    image: "/placeholder.svg?height=24&width=24",
    description: "AI decentralized computing network",
    chain: "Solana",
    cost: "Ended",
    backers: "Multicoin Capital, Solana Ventures, OKX Ventures, etc.",
    stage: "Mainnet",
  },
  {
    id: "5",
    name: "Tabi",
    image: "/placeholder.svg?height=24&width=24",
    description: "Modular Cosmos Gaming Chain",
    chain: "BNB",
    cost: "FREE",
    backers: "Binance Labs, Animoca Brands, etc.",
    stage: "Mainnet",
  },
  {
    id: "6",
    name: "Warpcast(Farcaster)",
    image: "/placeholder.svg?height=24&width=24",
    description: "Crypto Social Network",
    chain: "Base",
    cost: "FREE",
    backers: "a16z, Coinbase Ventures, etc.",
    stage: "Mainnet",
  },
  {
    id: "7",
    name: "Lava Network",
    image: "/placeholder.svg?height=24&width=24",
    description: "Modular Data Network",
    chain: "Multichain",
    cost: "FREE",
    backers: "Jump Crypto, Hashkey, etc.",
    stage: "Testnet",
  },
  {
    id: "8",
    name: "Karak",
    image: "/placeholder.svg?height=24&width=24",
    description: "Risk Management & AI Infrastructure",
    chain: "Independent",
    cost: "Bridge Liquidity",
    backers: "Pantera Capital, Framework Ventures, etc.",
    stage: "Mainnet",
  },
  {
    id: "9",
    name: "Blast",
    image: "/placeholder.svg?height=24&width=24",
    description: "Ethereum Layer-2",
    chain: "Ethereum/EVM",
    cost: "Bridge Liquidity",
    backers: "Standard Crypto, EGirl Capital, Mechanism Capital, etc.",
    stage: "Mainnet",
  },
  {
    id: "10",
    name: "Linea",
    image: "/placeholder.svg?height=24&width=24",
    description: "Ethereum Layer-2",
    chain: "Ethereum/EVM",
    cost: "Gas Fees",
    backers: "Consensys",
    stage: "Mainnet",
  },
]

